### PR TITLE
Support stream_select()

### PR DESCRIPTION
**Pull request by alexpott**
Don't error on stream_select() - we can return the original resource.

### CODE REVIEW

**Comment by alexpott** [comment]
This doesn't work :(

**Comment by alexpott** [comment]
I need to write tests and find something that does.

**Comment by ohader** [comment]
Interesting, what was your idea and approach on using `stream_select`?

**Comment by ohader** [comment]
I read the comments at https://www.drupal.org/project/drupal/issues/3026560 but failed to see how Phar archives might be involved in `stream_select`. Looking forward to getting some additional feedback on how Drupal or Drush is making use of it.

**Comment by ohader** [comment]
Is this one still required? If yes, what would the scenario look like that shall be solved? Thx in advance for feedback!

**Comment by alexpott** [comment]
Drupal users using drush have definitely experienced the error thrown by this method so we do have a way of causing it. However somewhat annyoingly I've never managed to reproduce it. Drush (Drupal's shell tool) has functionality to connect to remote servers and run commands there. I suspect that this is occurring when it is being used to do that but I've not managed to prove that.

**Comment by ohader** [comment]
Just for the records: https://github.com/php/php-src/blob/master/ext/standard/tests/file/userstreams_002.phpt

**Comment by ohader** [comment]
Thus, having something in source code does not feel correct in general (most probably that's trigger by Drush, caches, whatever)

```
    $pointer = fopen('phar://storage/bundle.phar/Resources/content.txt', 'r');
    $read = [$pointer];
    $write = null;
    $except = null;
    $events = stream_select($read, $write, $except, 3);
```

The following replacement for `PharStreamWrapper::stream_cast` would "solve" the issue, however actually selecting from a Phar stream is not expected - it's just a work-around for possible code flaws in other components

```
    /**
     * @param int $cast_as
     */
    public function stream_cast($cast_as)
    {
        return STDIN;
    }
```

**Comment by ohader** [comment]
In https://www.drupal.org/project/drupal/issues/3026560#comment-12931921 I found pointers to `DrushInputAdapter` and `ClassLoader`, but could not find any evidence there. Checking `stream_resolve_include_path` used in `ClassLoader` did not reveal anything new.

So... I still cannot reproduce this locally...

**Comment by hron84** [comment]
@ohader this resolved a lot of problems for me with [DRD Agent](https://drupal.org/project/drd_agent) module on PHP 5.6. Mostly this error caused on sites that run on PHP 5.6 and before you say: there is currently no way to switch from that version for us in those specific cases.

Please run your tests against PHP 5.6 and since Drupal 8.x still support this PHP version please provide some solution for this specific exception. Something, like checking phpversion() and returning with STDIN, would work.

**Comment by ohader** [comment]
@hron84 I was playing around with different old PHP 5.6 versions (`5.6.x-cli` as Docker image) but failed to reproduce the mentioned behavior (e.g. trying to setup Drush as well as process forking using `symfony/process` component).

https://www.drupal.org/project/drd_agent/issues/3039384 mentions
> [..] The patch in that other issue is just removing the function that throws the exception [..]
In case removing the whole `PharStreamWrapper::stream_cast` method helps, I could include that in one of the next releases - please just let me know whether that really solves the issue.

Side note in `STDIN` from above - which is really just a hack. I am reluctant in putting that into the package since `STDIN` is actually used then - including all new side effects that may be causing. For instance using the code of https://github.com/TYPO3/phar-stream-wrapper/pull/8#issuecomment-468914643 and focussing on the result of `$events` changes with a simple experiment in CLI:

* `php example.php` has `$events: 0`
* `php example.php < example.php` has `$events: 1` - sure since there is real `STDIN`

**Comment by hron84** [comment]
I could be fine with it. I did not figured out what conditions trigger Drupal / DRD to use stream_cast but almost all our PHP 5.6 sites were affected in this issue. I had to manually hack them regardless if they're on Drupal 6, Drupal 7 or Drupal 8. If you say removing the method can help - I will absolute love this solution. As I said, I am not a PHP developer rather a sysadmin, from my aspect if the error will not came back then I can collect my profit.

**Comment by ohader** [comment]
Alright & thx for your feedback. I'm going to raise my question later in the DRD issue tracker as well...

**Comment by ohader** [comment]
Closed since it could not be directly reproduced with various PHP 5.6 Docker containers...

**Pull request closed without merging**
