### PR TITLE
Use appveyor to test on windows

### PR DESCRIPTION
**Pull request by alexpott**
As there are windows only issues see #36 how about adding a .appveyor integration for Windows testing?

This is nearly there. It includes #36 because it needs the public static Helper method...

### CODE REVIEW

**Comment by ohader** [comment]
Windows testing would be awesome (I do it manually on a VM currently)
So, I'd opt for merging #36 first and but this one on top if it

**Comment by alexpott** [comment]
So we're still failing on windows even with #36 having been merged - https://ci.appveyor.com/project/alexpott/phar-stream-wrapper/builds/24509709
```
There were 3 failures:
1) TYPO3\PharStreamWrapper\Tests\Functional\HelperTest::baseFileIsResolved with data set #3 ('phar://C:/projects/php-projec...nt.txt', 'C:/projects/php-project-works...e.phar')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'C:/projects/php-project-workspace/tests/Functional/Fixtures/Existing/../bundle.phar'
+'C:/projects/php-project-workspace/tests/Functional/Fixtures/Existing/../bundle.phar/path/..'
C:\projects\php-project-workspace\tests\Functional\HelperTest.php:79
2) TYPO3\PharStreamWrapper\Tests\Functional\HelperTest::baseFileIsResolved with data set #5 ('phar://C:/projects/php-projec...nt.txt', null)
Failed asserting that 'C:/projects/php-project-workspace/tests/Functional/Fixtures/NotExisting/../bundle.phar/path/..' is identical to null.
C:\projects\php-project-workspace\tests\Functional\HelperTest.php:79
3) TYPO3\PharStreamWrapper\Tests\Functional\Interceptor\PharExtensionInterceptorTest::cliToolIsExecuted with data set "C:/projects/php-project-workspace/tests/Functional/Fixtures/cli-tool" ('C:/projects/php-project-works...i-tool')
Failed asserting that null is identical to Array &0 (
    '__wrapped' => true
    '__self' => 'TYPO3 demo text file.'
    '__alias' => 'TYPO3 demo text file.'
    'bundle.phar' => 'TYPO3 demo text file.'
).
C:\projects\php-project-workspace\tests\Functional\Interceptor\PharExtensionInterceptorTest.php:122
--
```

**Comment by ohader** [comment]
Obviously `var_dump(is_file('README.md/nothing/..'));` works on Windows, but not on Unix (as expected).

**Comment by ohader** [comment]
One failing (which works on my local Windows VM), maybe a `$PATH` issue with AppVeyor concering `php` binary?
```
1) TYPO3\PharStreamWrapper\Tests\Functional\Interceptor\PharExtensionInterceptorTest::cliToolIsExecuted with data set "C:/projects/php-project-workspace/tests/Functional/Fixtures/cli-tool" ('C:/projects/php-project-works...i-tool')
Failed asserting that null is identical to Array &0 (
    '__wrapped' => true
    '__self' => 'TYPO3 demo text file.'
    '__alias' => 'TYPO3 demo text file.'
    'bundle.phar' => 'TYPO3 demo text file.'
).
C:\projects\php-project-workspace\tests\Functional\Interceptor\PharExtensionInterceptorTest.php:122
```

**Comment by alexpott** [comment]
Yay we're green on appveyor! The last error turned out to be due to OS specific-ness of symlinks. So instead of adding the symlink to git we create it during the test and ignore it using .gitignore.

**Comment by alexpott** [comment]
See https://ci.appveyor.com/project/alexpott/phar-stream-wrapper/builds/24524986 🎉

**Comment by ohader** [comment]
Squashed commits... basically it's ready. Thx @alexpott

**Pull request merged**
